# Generated by Django 5.2.11 on 2026-03-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveIntegerField()),
                ('capacidad_carga_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_RUTA', 'En ruta'), ('MANTENIMIENTO', 'En mantenimiento'), ('FUERA_DE_SERVICIO', 'Fuerda de servicio')], default='DISPONIBLE', max_length=20)),
            ],
        ),
    ]
