# Generated by Django 5.2.11 on 2026-03-14 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('remitente_nombre', models.CharField(max_length=150)),
                ('remitente_telefono', models.CharField(blank=True, max_length=30)),
                ('remitente_direccion', models.CharField(max_length=200)),
                ('consignatario_nombre', models.CharField(max_length=150)),
                ('destino', models.CharField(max_length=150)),
                ('valor_declarado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_bultos', models.PositiveBigIntegerField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
            ],
        ),
    ]
