# Generated by Django 5.2.11 on 2026-03-14 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remitos', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HojaDeRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chofer', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehiculos.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='HojaDeRutaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('hoja_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='remitos.hojaderuta')),
                ('remito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='remitos.remito', unique=True)),
            ],
        ),
    ]
