# Generated by Django 5.2.11 on 2026-03-14 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remitos', '0002_hojaderuta_hojaderutadetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojaderutadetalle',
            name='remito',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='remitos.remito'),
        ),
    ]
