# Generated by Django 5.2.11 on 2026-03-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remitos', '0003_alter_hojaderutadetalle_remito'),
    ]

    operations = [
        migrations.AddField(
            model_name='remito',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_ruta', 'En ruta'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
    ]
