# Generated by Django 5.2.11 on 2026-03-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remitos', '0004_remito_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojaderuta',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
